[package]
name = "docker_engine_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "*"
curl = "*"
hyper = { version = "*", features = ["client", "http1"] }
tokio = { version = "*", features = ["net", "rt"] } 
